### ISSUE TITLE
OpenBSD Build Failure w/ openssl-sys 0.9.46

### ISSUE THREAD

**Issue by protoCall7** [getzola/zola#684]
# Bug Report

## Environment

Zola version: 0.7.0
OS: OpenBSD-current

## Expected Behavior
Zola should build correctly on OpenBSD

## Current Behavior
openssl-sys is locked to v0.9.46 in Cargo.lock. The latest version of LibreSSL is not supported in this version, and will not build.

## Step to reproduce
1) Check out latest repo (master branch)
2) `cargo build --release`

## Workaround
Bumping the version of openssl-sys from v0.9.46 to v0.9.49 allows the build to complete successfully:

* `cargo update`
* `CXX=clang++ cargo build --release`

## Note
Defining `CXX=clang++` allows for the building of libsass in OpenBSD after fixing the dependency issue reported above. I was unable to get compilation to work correctly using g++ 8.0.3 from the package repository. `gmake` is a hard requirement.

edit: removing the `p openssl-sys`, as updating it on it's own causes different breakage.

**Comment by protoCall7** [comment]
I have access to multiple OpenBSD-current machines and would be happy to test any updates to fix this problem if the dev team doesn't have any OpenBSD-current systems.

**Comment by Keats** [comment]
Thanks for the offer I'll take it!
I'll `cargo update` the `next` branch after merging some PRs and it should be hopefully working.

**Comment by Keats** [comment]
@protoCall7 can you try building the `next` branch? I don't expect many more changes than what's currently in it

**Comment by protoCall7** [comment]
@Keats unfortunately, I have run into another problem that I wasn't seeing before. When trying to build, the openssl and openssl-sys crates build fine, but pulldown-cmark is now failing, seemingly due to use of unstable features:

```
$ cargo build --release 
   Compiling syn v0.15.37
   Compiling pulldown-cmark v0.5.2
error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.5.2/src/scanners.rs:24:5
   |
24 | use std::convert::TryInto;
   |     ^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.5.2/src/scanners.rs:624:31
    |
624 |     let mut codepoint = input.try_into().ok()?;
    |                               ^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `pulldown-cmark`.

To learn more, run the command again with --verbose.
```

I also noticed that OpenBSD-current (nightly developer build) has updated from LibreSSL 2.9.x to 3.0.0, which is unsupported by the openssl crate. Due to this, I performed the testing above on an OpenBSD 6.5 machine (latest stable release).

As far as the OpenBSD 6.5 support is concerned, would this new error have possibly been caused by the update? Is nightly rust required to build Zola?

**Comment by Keats** [comment]
TryInto has been stabilised in 1.34 iirc, Zola is built using stable.

**Comment by protoCall7** [comment]
That would explain the differences. In OpenBSD 6.5, we have Rust 1.33.0 with LibreSSL 2.9.1, with your changes this allows openssl-sys to build, but not pulldown-cmark.

In OpenBSD-current, we have Rust 1.35.0 with LibreSSL 3.0.0, so pulldown-cmark builds fine, but openssl-sys does not.

I would anticipate that when LibreSSL 3.0.0 becomes the stable release (likely with the OpenBSD 6.6 release this fall), openssl-sys will add support and the build should go back to working as expected.

Because Rust does not distribute OpenBSD compatible binaries, rustup is not included with our distribution, so I am stuck with 1.33.0 on the stable release for the time being.

**Comment by Keats** [comment]
Closing as this is now an issue of OS being on older version of Rust.

**Comment by dertuxmalwieder** [comment]
I noticed that the `openssl-sys` crate does not even work with new versions of OpenBSD and Rust, because OpenBSD’s very own LibreSSL is almost always ahead of the crate’s known library versions... and the `openssl` crate (which would fix it on other systems) is is already [two versions behind](https://github.com/sfackler/rust-openssl/issues/1309).

OpenBSD is a [Tier 3 platform](https://doc.rust-lang.org/nightly/rustc/platform-support.html), so the general situation of Rust tooling on OpenBSD is unlikely to change soon. By the way, it does not work too well on an illumos (ex-OpenSolaris) system either, so I can imagine similar reports for other platforms.

**Comment by protoCall7** [comment]
@dertuxmalwieder sorry for the slow response. `openssl-sys` is always going to be a moving target for OpenBSD, especially against OpenBSD-current because of LibreSSL, as you noted. These days this issue shows itself much more during local builds with cargo than during builds from the ports system, as the `devel/cargo` ports module is automatically patching crates that are known to have issues like this (which is new behavior since I initially opened this issue for Zola 0.7.0). Here's where `openssl-sys` gets fixed by the ports system now:

https://github.com/openbsd/ports/blob/master/devel/cargo/cargo.port.mk#L132-L138

**Comment by dertuxmalwieder** [comment]
Ah, lovely - I had not known that. I will know better in the future. :-) Thank you!

**Comment by Keats** [comment]
(we don't have openssl in the dep tree anymore btw)
